#!/usr/bin/env bash
#
# THE DEPLOYER 9000
# 
# DESCRIPTION: 	A lightweight code deployer for CI/CD
#				Deploy your code via GitHub actions with just couple of lines
# 
# VERSION: 		1.0
# DATE: 		2025-08-08 
# AUTHOR: 		Black HOST Ltd.
# ######################################################################################################################
#

set -euo pipefail

# load all submodules
for f in /usr/share/deployer/*.sh; do source "$f"; done

## PROTOCOL ROUTER
run_remote_command "${PRE_SCRIPT:-}" "pre-deploy"

case "$PROTOCOL" in

	ftp)	FTP;;
	sftp) 	SFTP;;
	rsync)	RSYNC;;

	*)		die "Unsupported protocol: $PROTOCOL (expected ftp|sftp|rsync|ssh)";;

esac

# execute post-deploy script
run_remote_command "${POST_SCRIPT:-}" "post-deploy"

ok "Yatta! The deployment has been complted."