#!/usr/bin/env bash
#
# THE DEPLOYER 9000
# 
# DESCRIPTION: 	A lightweight code deployer for CI/CD
#				Deploy your code via GitHub actions with just couple of lines
# 
# VERSION: 		1.0
# DATE: 		2025-08-08 
# AUTHOR: 		Black HOST Ltd.
# ######################################################################################################################
#

set -euo pipefail

# load all submodules
for f in /usr/share/deployer/*.sh; do source "$f"; done

## PROTOCOL ROUTER
case "$PROTOCOL" in

	ftp)
		FTP
	;;

	sftp)
		SFTP
	;;

	*)
		die "Unsupported protocol: $PROTOCOL (expected ftp|sftp|ssh)"
	;;

esac

log "Yatta! The deployment has been complted."